--test view with math function
CREATE VIEW projects AS SELECT
PROJECT_DATE_CREATION,
PROJECT_TIME_CREATION,
PROJECT_TERM_DELIVERY,
PROJECT_COST_DELIVERY,
PROJECT_NAME,
PROJECT_DESCRIPTION,
PROJECT_COST_DELIVERY * currencies.CURRENCY_EXCHANGE_RATE AS BYN
FROM projects 
INNER JOIN currencies ON currencies.CURRENCY_ID = projects.PROJECT_CURRENCY_ID 
GROUP BY PROJECT_DATE_CREATION, PROJECT_TIME_CREATION,PROJECT_TERM_DELIVERY,PROJECT_COST_DELIVERY,PROJECT_NAME,PROJECT_DESCRIPTION,currencies.CURRENCY_EXCHANGE_RATE;
 ------------------------
  
  CREATE VIEW projects AS SELECT
users.USER_NICKNAME,
PROJECT_DATE_CREATION,
PROJECT_TIME_CREATION,
PROJECT_TERM_DELIVERY,
PROJECT_COST_DELIVERY,
PROJECT_NAME,
PROJECT_DESCRIPTION,
FROM projects 
INNER JOIN currencies ON currencies.CURRENCY_ID = projects.PROJECT_CURRENCY_ID
INNER JOIN users ON users.USER_ID = projects.PROJECT_USER_ID


CREATE VIEW risks AS SELECT
RISK_LOSS_INCOME,
RISK_LOSS_TIME_INDAY,
RISK_NAME,
RISK_AVAILABILITY_ID
FROM risks

CREATE VIEW tasks AS SELECT
TASK_NAME,
TASK_NOTE,
TASK_STATE_ID,
TASK_PRIORITY_ID
FROM tasks

CREATE VIEW users AS SELECT
USER_NAME,
USER_SURNAME,
USER_PATRONYMIC,
USER_PASSWORD,
USER_IMG,
USER_PHONE,
USER_EMAIL
FROM users


















